name = "forgecon-auth"
main = "worker/index.js"
compatibility_date = "2025-05-01"
routes = [{ pattern = "api.forgecon.com.br", custom_domain = true }]

[vars]
ORIGIN_CEP = "03810110"

[[d1_databases]]
binding = "DB"
database_name = "forgecon-db"
database_id = "d29af0d6-23a8-4d03-95ad-0b12dcfb0bd4"
